### PR TITLE
Continuous intragration with Unit Tests

### PR DESCRIPTION
**Pull request by prashantvc**
Changes Proposed in this pull request:
- Added the contribution guide and PR check list
- Added the script to initiate and run automated unit tests for iOS and Android

### CODE REVIEW

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
Did you mean to check in the exe?

**Comment by prashantvc** [comment]
> Did you mean to check in the exe?

Yes. There are two exes in the PR
**Touch.Server.exe** it is required to launch iOS tests on Simulator/Device and retrieve test results. This necessary and required.

**nunit-summary.exe** outputs the XML tests results in readable format. This is not really necessary but it helps when you want to run tests on local machine

**Comment by jamesmontemagno** [comment]
Hmmm I am curious if we can download them via a script instead of checking them in. This is what i usually do in the build scripts.

**Comment by prashantvc** [comment]
Yes, that's a good idea, we could do that
I will make changes to the script :)

**Review by jamesmontemagno — APPROVED** [review]

**Pull request merged**
